# Generated by Django 3.0.3 on 2020-03-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getinfo', '0002_auto_20200323_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='roll',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
